package wzl.ebook.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import wzl.ebook.entity.Orderitem;

public interface OrderitemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitem
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("orderId") Integer orderId, @Param("bookId") Integer bookId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitem
     *
     * @mbg.generated
     */
    int insert(Orderitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitem
     *
     * @mbg.generated
     */
    Orderitem selectByPrimaryKey(@Param("orderId") Integer orderId, @Param("bookId") Integer bookId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitem
     *
     * @mbg.generated
     */
    List<Orderitem> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitem
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Orderitem record);
}